version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
install:
- cmd: >-
    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

    nmake restore
build_script:
- cmd: >-
    nmake

    nmake deploy
artifacts:
  - path: Koturn.CommandLine-netstandard2.0.zip
    name: Koturn.CommandLine-netstandard2.0
  - path: Koturn.CommandLine-net8.0.zip
    name: Koturn.CommandLine-net8.0
  - path: Koturn.CommandLine-net9.0.zip
    name: Koturn.CommandLine-net9.0
  - path: Koturn.CommandLine-net10.0.zip
    name: Koturn.CommandLine-net10.0
